name = "BlockHaloArrays"
uuid = "8029ca6b-11ad-4a59-88a2-2e6eee4ef8a2"
authors = ["Sam Miller <smil@lle.rochester.edu> and contributors"]
version = "0.1.0"

[deps]
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NumaAllocators = "21436f30-1b4a-4f08-87af-e26101bb5379"
ThreadPinning = "811555cd-349b-4f26-b7bc-1f208b848042"
ThreadPools = "b189fb0b-2eb5-4ed4-bc0c-d34c51242431"

[compat]
EllipsisNotation = "1"
ThreadPinning = "0.4"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
